Pterodactyl widget: initial commit
benphelps/homepage pull request #1026
Opened 2023-02-20 13:45 UTC by Oupsman

Widget has two fields:
Nodes (Online/Total)
Servers (Running/Total)

## Proposed change

Closes # (issue)

## Type of change

- [X] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [ ] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: https://github.com/benphelps/homepage-docs/pull/40
- [ ] 
- [X] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2023-02-20 23:13 UTC, shamoon commented
Please provide sample API output, this doesn't seem trivial to setup which is always challenging with a custom proxy.

Speaking of which, there are some issues with it, I will leave comments but again ideally we could test against the app.

2023-02-20 23:16 UTC, shamoon requested changes

2023-02-20 23:16 UTC, shamoon commented on src/widgets/pterodactyl/proxy.js
> +        // eslint-disable-next-line no-await-in-loop
The reason this throws a lint error is because using await inside a loop doesn't work like you think it does. You likely need to use `Promise.all`. In general with these if you google the error you'll get a good explanation, e.g. https://eslint.org/docs/latest/rules/no-await-in-loop

2023-02-20 23:16 UTC, shamoon commented on src/widgets/pterodactyl/proxy.js
> +      /* eslint-disable no-await-in-loop */
Same as above https://eslint.org/docs/latest/rules/no-await-in-loop

2023-02-20 23:16 UTC, shamoon commented on src/widgets/pterodactyl/proxy.js
> +      for (let nodeid = 0; nodeid < nodesData.data.length; nodeid += 1) {
So do we have any idea of the potential number of API calls this could make? Obviously I don't use the software but Im guessing its generally low, but...

2023-02-21 00:14 UTC, JazzFisch commented
@Oupsman can you please provide some guidance on how we can test all of this?

2023-02-21 07:39 UTC, Oupsman commented on src/widgets/pterodactyl/proxy.js
> +      for (let nodeid = 0; nodeid < nodesData.data.length; nodeid += 1) {
In the current state of the API, there is no way to get all the statuses of the servers in one API call, sadly. 

So this code makes 2 calls per node (one to get the general information and the server list, the other to verify if it is online) and one API call per server, to get the server status. On very busy pterodactyl servers,it can make a great number of API calls.

2023-02-21 07:45 UTC, Oupsman commented on src/widgets/pterodactyl/proxy.js
> +        // eslint-disable-next-line no-await-in-loop
OK got it, I'll work on that.

2023-02-21 07:46 UTC, Oupsman commented
For testing, I can give you an access to my personnal server, just give me an email address for me to send the configuration to.

2023-02-22 16:51 UTC, shamoon commented
Thanks for the offer to use your setup, we may need to take you up on that but before that I think there’s still a fundamental question about the plan to hit each node multiple times. Simply put, I don’t think something like that belongs in homepage. These widgets are meant to be quick performant informational widgets.

If you remove the node calls, can you still get any useful information from the main server?

2023-02-22 20:46 UTC, shamoon commented
Hey @Oupsman , please see my last commit. As usual **this is just a suggestion, you can always revert the change**. Essentially it just shows node and server count. I realize it makes the widget less useful but it also avoids the issue above and doesn't require a custom proxy any more.

I did get a very basic pterodactyl instance setup but nothings really working so I can only test it out so much.

Again, let us know your thoughts, if you're not happy with this the change can be reverted but I don't currently see an alternate pathway to get the 'online' info that isn't so cumbersome...

2023-02-22 21:12 UTC, Oupsman commented
I liked the idea of having an information of the online nodes and the started servers, but I really understand your concerns and I agree with you : better not to use any proxy code. 

Why don't we publish the widget as you propose, and see if someone requests some more informations ?

2023-02-22 21:40 UTC, shamoon commented
That sounds reasonable, thanks for your understanding. Does the code work as-is for you? Again my instance is kind of a 'dummy' one.

2023-02-24 03:42 UTC, shamoon approved these changes

2023-02-24 15:53 UTC, merged