Add Support for Simple Icons + Add optional theme colors for icons
benphelps/homepage pull request #1438
Opened 2023-05-01 01:21 UTC by davidsmejia

## Proposed change

I was setting up my homepage bookmarks to use material icons and there were two things that I wanted to address. The mask gradient wasn't the aesthetic I was going for and I saw a deprecation warning for most if not all of the brand icons in the material design icon set that I wanted to use.

I didn't look to see when the deprecation will go into effect but I don't think it hurts to implement something like this ahead of time.

Deprecation warning can be seen here; https://pictogrammers.com/library/mdi/icon/reddit/
Github Issue from maintainer with list: https://github.com/Templarian/MaterialDesign/issues/4901

### Simple Icon Support
I wanted to add support for simple-icons as suggested in the message from the mdi maintainer. The way that I implemented it anticipates support for other prefixes and should be completely backwards compatible. Essentially you can opt in to use the `si-` prefix and when mdi removes their brand icons, the `si-` prefix will still work.

### iconStyle Proposal
The proposed setting is called `iconStyle`, which defaults to `gradient` but can optionally be set to `theme`. Gradient behaves exactly as before and the new theme option will use the same css rule as the text for whichever theme is used. I thought this would be the most compliant implementation.

I am open to feedback and changes, the code style is a bit different than mine but I tried to conform to existing conventions. Let me know if you would like me to change anything. If you only want one of these changes, I would be happy to resubmit per your request.

Also if you would like a PR for the documentation before this is merged let me know.

Here are some example screen shots, there are obviously a lot of permutation but I think is is representative of the changes.

![mdi-](https://user-images.githubusercontent.com/1075609/235384157-a3e12645-6582-4ad2-af80-a53748c22da1.PNG)
mdi- and settings.iconStyle = "gradient" 

![mdi-theme](https://user-images.githubusercontent.com/1075609/235384158-0d662fbc-d23b-4c9c-b7c9-832cf18a9188.PNG)
mdi- prefix and settings.iconStyle = "theme"

![mdi-theme-light](https://user-images.githubusercontent.com/1075609/235384159-28fd246b-c907-4be6-9397-8dd4b5f7e7c1.PNG)
theme="light" and settings.iconStyle = "theme"

![si-](https://user-images.githubusercontent.com/1075609/235384160-6025318b-a623-461c-8305-3e91daf37837.PNG)
Bookmark Simple Icon with settings.iconStyle not specified

![si-service-dark](https://user-images.githubusercontent.com/1075609/235384161-07aa434a-a9da-4697-ac4b-378a9dfc7390.PNG)
Service Simple Icons with settings.iconStyle="theme"

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Other (please explain)
  - Future bug fix + new feature

## Checklist:

- [ ] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: 
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2023-05-01 15:18 UTC, shamoon commented
Thanks for the PR.

That deprecation notice is 3y old, ha. Are there other reasons to support simple icons? Also to be clear youre saying that if that time ever comes this will still break but the answer will be "just change your mdi-reddit to si-reddit"?

I like the theme option.

Please submit a doc PR for this.

2023-05-01 16:43 UTC, davidsmejia commented
> Are there other reasons to support simple icons? 

Yeah, at least for me there are some icons I'd like to use for bookmarks that aren't available in mdi.

> Also to be clear youre saying that if that time ever comes this will still break but the answer will be "just change your mdi-reddit to si-reddit"?

Yeah... I thought it would be best to keep existing behavior the same. I didn't think it made sense to implement a test for the icon then load the SI icon if that fails. I will mention this is the documentation when I PR for that.

Method used compare the icon sets:
pbpaste contents is the html table from the cdn 
```bash 
$ pbpaste | grep nofollow | awk '{$1=$1};1' | | awk -F'>' '{print $2}' | awk -F '<' '{print $1}' > material-icons
$ pbpaste | grep nofollow | awk '{$1=$1};1' | | awk -F'>' '{print $2}' | awk -F '<' '{print $1}' > simple-icons
$ comm -23 simple-icons material-icons > only-simple-icons
$ wc -l only-simple-icons
# 2310 only-simple-icons
```

<details><summary>Contents of only-simple-icons</summary>
<p>
1password.svg
3m.svg
4chan.svg
4d.svg
42.svg
500px.svg
1001tracklists.svg
abbott.svg
abbrobotstudio.svg
abbvie.svg
abletonlive.svg
aboutdotme.svg
abstract.svg
academia.svg
accenture.svg
acclaim.svg
accusoft.svg
acer.svg
acm.svg
actigraph.svg
activision.svg
adafruit.svg
adblock.svg
adblockplus.svg
addthis.svg
adguard.svg
adidas.svg
adminer.svg
adobe.svg
adobeacrobatreader.svg
adobeaftereffects.svg
adobeaudition.svg
adobecreativecloud.svg
adobedreamweaver.svg
adobefonts.svg
adobeillustrator.svg
adobeindesign.svg
adobelightroom.svg
adobelightroomclassic.svg
adobephotoshop.svg
adobepremierepro.svg
adobexd.svg
adonisjs.svg
adp.svg
adyen.svg
aerlingus.svg
aeroflot.svg
aeromexico.svg
aerospike.svg
aew.svg
affine.svg
affinity.svg
affinitydesigner.svg
affinityphoto.svg
affinitypublisher.svg
aframe.svg
agora.svg
aib.svg
aidungeon.svg
aiohttp.svg
aiqfome.svg
airasia.svg
airbnb.svg
airbus.svg
airbyte.svg
aircall.svg
aircanada.svg
airchina.svg
airfrance.svg
airplayaudio.svg
airplayvideo.svg
airtable.svg
ajv.svg
akamai.svg
alacritty.svg
albertheijn.svg
alchemy.svg
aldinord.svg
aldisud.svg
alfaromeo.svg
alfred.svg
algolia.svg
algorand.svg
alibabacloud.svg
alibabadotcom.svg
aliexpress.svg
alipay.svg
alitalia.svg
allegro.svg
alliedmodders.svg
allocine.svg
alltrails.svg
alpinedotjs.svg
alpinelinux.svg
altiumdesigner.svg
alwaysdata.svg
amazon.svg
amazonalexa.svg
amazonapigateway.svg
amazonaws.svg
amazoncloudwatch.svg
amazondynamodb.svg
amazonec2.svg
amazonecs.svg
amazoneks.svg
amazonfiretv.svg
amazongames.svg
amazonlumberyard.svg
amazonpay.svg
amazonprime.svg
amazonrds.svg
amazons3.svg
amazonsqs.svg
amd.svg
americanairlines.svg
americanexpress.svg
amg.svg
amp.svg
amul.svg
ana.svg
anaconda.svg
analogue.svg
andela.svg
androidauto.svg
androidstudio.svg
angellist.svg
angularuniversal.svg
anilist.svg
answer.svg
ansys.svg
anta.svg
antdesign.svg
antena3.svg
anydesk.svg
aol.svg
apache.svg
apacheairflow.svg
apacheant.svg
apachecassandra.svg
apachecloudstack.svg
apachecordova.svg
apachecouchdb.svg
apachedruid.svg
apacheecharts.svg
apacheflink.svg
apachegroovy.svg
apachehadoop.svg
apachehive.svg
apachejmeter.svg
apachekafka.svg
apachekylin.svg
apachemaven.svg
apachenetbeanside.svg
apacheopenoffice.svg
apachepulsar.svg
apacherocketmq.svg
apachesolr.svg
apachespark.svg
apachetomcat.svg
aparat.svg
apollographql.svg
apostrophe.svg
appian.svg
applearcade.svg
applemusic.svg
applenews.svg
applepay.svg
applepodcasts.svg
appletv.svg
appsignal.svg
appstore.svg
appveyor.svg
appwrite.svg
aqua.svg
aral.svg
arangodb.svg
arcgis.svg
archicad.svg
archiveofourown.svg
archlinux.svg
ardour.svg
arduino.svg
argo.svg
argos.svg
arkecosystem.svg
arlo.svg
arm.svg
artifacthub.svg
artixlinux.svg
arxiv.svg
asana.svg
asciidoctor.svg
asciinema.svg
asda.svg
aseprite.svg
askfm.svg
askubuntu.svg
assemblyscript.svg
astonmartin.svg
astro.svg
asus.svg
atandt.svg
atari.svg
auchan.svg
audacity.svg
audi.svg
audible.svg
audioboom.svg
audiomack.svg
audiotechnica.svg
aurelia.svg
auth0.svg
authy.svg
autodesk.svg
autohotkey.svg
automattic.svg
autoprefixer.svg
avajs.svg
avast.svg
awesomelists.svg
awesomewm.svg
awsamplify.svg
awsfargate.svg
awslambda.svg
axios.svg
azureartifacts.svg
azuredataexplorer.svg
azuredevops.svg
azurefunctions.svg
azurepipelines.svg
backblaze.svg
backbonedotjs.svg
backendless.svg
backstage.svg
badgr.svg
badoo.svg
baidu.svg
bamboo.svg
bandcamp.svg
bandlab.svg
bandrautomation.svg
bandsintown.svg
bankofamerica.svg
barclays.svg
baremetrics.svg
basecamp.svg
bastyon.svg
bata.svg
bathasu.svg
battledotnet.svg
bbc.svg
bbciplayer.svg
beatport.svg
beats.svg
beatsbydre.svg
behance.svg
beijingsubway.svg
bem.svg
bentley.svg
betfair.svg
bigbasket.svg
bigbluebutton.svg
bigcartel.svg
bigcommerce.svg
bilibili.svg
bim.svg
binance.svg
biolink.svg
bit.svg
bitcoincash.svg
bitcoinsv.svg
bitdefender.svg
bitly.svg
bitrise.svg
bitwarden.svg
bitwig.svg
blackberry.svg
blazemeter.svg
blazor.svg
blockchaindotcom.svg
blogger.svg
bloglovin.svg
blueprint.svg
bmcsoftware.svg
bmw.svg
boardgamegeek.svg
boehringeringelheim.svg
boeing.svg
bookalope.svg
bookbub.svg
bookmeter.svg
bookmyshow.svg
bookstack.svg
boost.svg
boots.svg
borgbackup.svg
bosch.svg
bose.svg
boulanger.svg
bower.svg
boxysvg.svg
brandfolder.svg
brave.svg
breaker.svg
britishairways.svg
broadcom.svg
bt.svg
buddy.svg
budibase.svg
buefy.svg
buffer.svg
bugatti.svg
bugcrowd.svg
bugsnag.svg
buildkite.svg
bukalapak.svg
bun.svg
bunq.svg
burgerking.svg
burton.svg
buymeacoffee.svg
buzzfeed.svg
bvg.svg
byjus.svg
byte.svg
bytedance.svg
c.svg
cachet.svg
cafepress.svg
caffeine.svg
cairographics.svg
cairometro.svg
cakephp.svg
campaignmonitor.svg
canonical.svg
canva.svg
capacitor.svg
cardano.svg
carrefour.svg
carthrottle.svg
carto.svg
cashapp.svg
castbox.svg
castorama.svg
castro.svg
caterpillar.svg
cbs.svg
cdprojekt.svg
celery.svg
ceph.svg
cesium.svg
chai.svg
chainguard.svg
chainlink.svg
chakraui.svg
chartdotjs.svg
chartmogul.svg
chase.svg
chatbot.svg
checkio.svg
checkmarx.svg
chef.svg
chemex.svg
chevrolet.svg
chinaeasternairlines.svg
chinasouthernairlines.svg
chocolatey.svg
chromecast.svg
chrysler.svg
chupachups.svg
cilium.svg
cinema4d.svg
circleci.svg
circuitverse.svg
cirrusci.svg
cisco.svg
citrix.svg
citroen.svg
civicrm.svg
civo.svg
ckeditor4.svg
claris.svg
clickhouse.svg
clickup.svg
clion.svg
cliqz.svg
clockify.svg
clojure.svg
cloud66.svg
cloudbees.svg
cloudcannon.svg
cloudera.svg
cloudflare.svg
cloudflarepages.svg
cloudfoundry.svg
cloudsmith.svg
cloudways.svg
clubhouse.svg
clyp.svg
cmake.svg
cncf.svg
cnn.svg
cocacola.svg
cockpit.svg
cockroachlabs.svg
cocoapods.svg
cocos.svg
coda.svg
codacy.svg
codeberg.svg
codecademy.svg
codeceptjs.svg
codechef.svg
codeclimate.svg
codecov.svg
codefactor.svg
codeforces.svg
codeigniter.svg
codemagic.svg
codemirror.svg
codenewbie.svg
codeproject.svg
codereview.svg
codersrank.svg
coderwall.svg
codesandbox.svg
codeship.svg
codewars.svg
codingame.svg
codingninjas.svg
codio.svg
coffeescript.svg
cognizant.svg
coil.svg
coinbase.svg
coinmarketcap.svg
commerzbank.svg
commitlint.svg
commodore.svg
commonworkflowlanguage.svg
composer.svg
comsol.svg
conan.svg
concourse.svg
condaforge.svg
conekta.svg
confluence.svg
construct3.svg
consul.svg
contactlesspayment.svg
containerd.svg
contao.svg
contentful.svg
conventionalcommits.svg
convertio.svg
cookiecutter.svg
coop.svg
cora.svg
coronaengine.svg
coronarenderer.svg
corsair.svg
couchbase.svg
counterstrike.svg
countingworkspro.svg
coursera.svg
coveralls.svg
cpanel.svg
cplusplus.svg
craftcms.svg
cratedb.svg
crayon.svg
createreactapp.svg
creativecommons.svg
creativetechnology.svg
credly.svg
crehana.svg
criticalrole.svg
crowdin.svg
crowdsource.svg
crunchbase.svg
crunchyroll.svg
crystal.svg
csharp.svg
css3.svg
cssmodules.svg
csswizardry.svg
cts.svg
cucumber.svg
cultura.svg
curl.svg
curseforge.svg
cycling74.svg
cypress.svg
cytoscapedotjs.svg
d.svg
d3dotjs.svg
dacia.svg
daf.svg
dailymotion.svg
daimler.svg
daisyui.svg
dapr.svg
darkreader.svg
dart.svg
darty.svg
daserste.svg
dash.svg
dashlane.svg
dask.svg
dassaults [...]

2023-05-01 16:53 UTC, shamoon commented
> I didn't think it made sense to implement a test for the icon then load the SI icon if that fails.

No, agree there, just mentioning. And yes would be good to note in the docs.

2023-05-01 17:11 UTC, shamoon requested changes
Small things

2023-05-01 17:11 UTC, shamoon commented on src/components/resolvedicon.jsx
> +          background,
```suggestion
          background: settings.iconStyle === "theme" ?
            `rgb(var(--color-${ theme === "dark" ? 300 : 900 }) / var(--tw-text-opacity))` :
            "linear-gradient(180deg, rgb(var(--color-logo-start)), rgb(var(--color-logo-stop)))",
```

2023-05-01 17:11 UTC, shamoon commented on src/components/resolvedicon.jsx
> +
```suggestion
const iconSetURLs = {
  'mdi': "https://cdn.jsdelivr.net/npm/@mdi/svg@latest/svg/",
  'si' : "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/",
};

```

2023-05-01 17:11 UTC, shamoon commented on src/components/resolvedicon.jsx
> +  };
```suggestion
```

2023-05-01 17:11 UTC, shamoon commented on src/components/resolvedicon.jsx
> +    const iconSource = `${prefixPaths[prefix]}${iconName}.svg`;
```suggestion
  if (prefix in iconSetURLs) {
    // get icon source
    const iconName = icon.replace(`${prefix}-`, "").replace(".svg", "");
    const iconSource = `${iconSetURLs[prefix]}${iconName}.svg`;
```

2023-05-01 17:19 UTC, shamoon approved these changes

2023-05-01 17:58 UTC, davidsmejia commented
Docs are here: https://github.com/benphelps/homepage-docs/pull/87

2023-05-01 18:06 UTC, merged

2023-05-03 22:40 UTC, Mega-Volti commented
This is amazing! Love to be able to have more icons to chose from and to be able to turn off the gradient.

Is there maybe a way to expand this in order to not only turn off the gradient, but also be able to set an icon color for each icon individually? E.g. pass a color code at the end of the icon name (si-icon_name-123456) and if that's detected, the color for that icon alone is set?