Add Tailscale Widget
benphelps/homepage pull request #1468
Opened 2023-05-06 15:09 UTC by andrejarrell

## Proposed change

This change introduces the new Tailscale widget that pulls stats from Tailscale's API.

![Screen Shot 2023-05-06 at 10 40 27](https://user-images.githubusercontent.com/33952641/236630866-c7784c3b-794f-4f1c-9e54-c7f57fc48065.png)

Add user would add the widget to the `services.yaml` file:
```yaml
widget:
    type: tailscale
    deviceid: deviceid
    key: tailscaleapikey
```

The Tailscale API is documented here:
https://github.com/tailscale/tailscale/blob/main/api.md#device

You can create an API access token on this page:
https://login.tailscale.com/admin/settings/keys

To find your device ID go to the Machines page:
https://login.tailscale.com/admin/machines
Select your machine, scroll down to "Machine Details" and copy the `ID`

The API request would look like this:

```http
GET https://api.tailscale.com/api/v2/device/xxxxx
Authorization: Bearer tskey-api-xxxxx
```

The API response would like this but we will only use `addresses`, `lastSeen`, `expires`:

```json
{
  "addresses": [
    "100.87.74.78",
    "fd7a:115c:a1e0:ac82:4843:ca90:697d:c36e"
  ],
  "name": "pangolin.tailfe8c.ts.net",
  "hostname": "pangolin",
  "clientVersion": "",
  "updateAvailable": false,
  "os": "linux",
  "created": "2022-12-01T05:23:30Z",
  "lastSeen": "2022-12-01T05:23:30Z",
  "keyExpiryDisabled": true,
  "expires": "2023-05-30T04:44:05Z",
  "authorized": true,
  "isExternal": true,
  "machineKey": "",
  "nodeKey": "nodekey:01234567890abcdef",
  "blocksIncomingConnections": false,
  "enabledRoutes" : [
    "10.0.0.0/16",
    "192.168.1.0/24",
  ],
  "advertisedRoutes" : [
    "10.0.0.0/16",
    "192.168.1.0/24",
  ],
  "tags": [
    "tag:golink"
  ],
  "tailnetLockError": "",
  "tailnetLockKey": "",
}
```

## Type of change

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [x] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: https://github.com/benphelps/homepage-docs/pull/90
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2023-05-06 15:15 UTC, shamoon requested changes
Thanks. Looks good overall and thanks for going through the FR first.

I will test later but noted some minor things here too.

2023-05-06 15:15 UTC, shamoon commented on src/widgets/tailscale/component.jsx
> +    return `${diff === "Now" ? diff : `${diff} Ago`}`;
This won't work with translation. You'll need to just return the number or now and in the block call the translation for any other strings like "y" and "Ago"

2023-05-06 15:15 UTC, shamoon commented on src/widgets/tailscale/component.jsx
> +    refreshInterval: 1000 * 60,
We currently don't allow service widgets to auto-refresh

2023-05-06 16:27 UTC, andrejarrell commented
@shamoon I have removed the `refreshInterval` and added translations for the time units and for `Ago`. Let me know if this is to your liking.

2023-05-07 04:09 UTC, shamoon commented
Cheers thanks for the contribution

2023-05-07 04:09 UTC, merged

2023-05-07 04:31 UTC, andrejarrell commented
@shamoon Thanks for adding the `now` and `never`. I was contemplating adding those. (First time working with those translations) I guess I misunderstood the change request for translation. Anyways, thanks for the prompt responses!