Add custom colors to resolvedicon.jsx
benphelps/homepage pull request #1724
Opened 2023-07-25 02:03 UTC by Mega-Volti

Enables appending a color code (e.g. "#123456") to all mdi and si icons, in order to change their color to a per-icon custom one.

## Proposed change

Closes # (issue)

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [ ] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: 
- [ ] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/en/more/development/#service-widget-guidelines).
- [ ] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2023-07-25 08:30 UTC, benphelps commented on src/components/resolvedicon.jsx
> +    if (suffix.match(`[#][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]`) == null) {
Should be an else statement here, instead of checking the suffix twice.

2023-07-25 08:49 UTC, Mega-Volti commented on src/components/resolvedicon.jsx
> +    if (suffix.match(`[#][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]`) == null) {
I had that first but then some check complained and it wouldn't compile properly when building the Dockerfile. This "ugly" check was the only way I got the Dockerfile to build, sadly.

2023-07-25 10:02 UTC, benphelps commented on src/components/resolvedicon.jsx
> +    if (suffix.match(`[#][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]`) == null) {
Ah right, don't wrap it in an if statement at all then, the if before it guards by returning when it matches.

2023-07-25 10:16 UTC, Mega-Volti commented on src/components/resolvedicon.jsx
> +    if (suffix.match(`[#][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]`) == null) {
Ah, right, I couldn't figure out why it didn't like the return-else, but I think I understand now. Fixed with the latest commit, and building the Dockerfile works now, thanks!

2023-07-25 14:27 UTC, shamoon commented on src/components/resolvedicon.jsx
> +
```suggestion
    if (suffix.test(`[#][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]`)) {

```

use `test` to check if a regex matches

2023-07-25 14:30 UTC, shamoon requested changes
Instead of one big if / else please change this to set the appropriate const's and the output the icon, i.e. DRY

2023-07-25 16:29 UTC, Mega-Volti commented on src/components/resolvedicon.jsx
> +
Done, and I also included upper case letters since the regex was case sensitive so far.

2023-07-25 17:20 UTC, Mega-Volti commented
> Instead of one big if / else please change this to set the appropriate const's and the output the icon, i.e. DRY

Updated. Although I had to switch from const to let. With const block scope, I had to repeat. Eliminating the repetition means I have to declare the variables outside of the if statement, hence no block scoped const, so I used let. I'm new to js, currently I don't see a better way, I'd be happy for pointers if I'm missing something.

Regarding the regex test: I updated my comment earlier and reverted the commit, the test function doesn't work on strings.

2023-07-25 17:34 UTC, shamoon commented
Please take a look at the last commit:

- Yea sorry that `test` snippet was written on my phone, it was incorrect as you noted
- Use regex literals
- Default vars to the current behavior and only change them if custom color detected

Let me know if you have any concerns or notice any issues

2023-07-25 21:45 UTC, Mega-Volti commented
Looks great, that matcher is indeed better, thanks!
No concerns or major issues from my side. I think I would have gone with an if..else statement to write the iconName and iconColor only once, instead of writing it and possibly overwiritng it again with a different value. But that's personal preference I guess. As long as it works, I'm very happy with it!

2023-07-26 00:31 UTC, shamoon approved these changes

2023-07-26 00:31 UTC, merged

2023-12-06 14:34 UTC, hex-developer commented
Hello @benphelps,
Is there a chance you will implement this feature for other svg icons? I want to use some custom icons (https://tabler-icons.io) and they show up black, which doesn't work very well with my dark theme! Alternatively you could also add built-in support for tabler icons. I might submit a PR at sone point.