OpenMediaVault widget
benphelps/homepage pull request #1807
Opened 2023-08-12 09:19 UTC by userXinos

## Proposed change

Widget for integration with OpenMediaVault (https://github.com/benphelps/homepage/discussions/1204)

![изображение](https://github.com/benphelps/homepage/assets/40886699/04b71373-d516-49f7-b95a-61045148ecc5)

OMV RPC docs: https://docs.openmediavault.org/en/6.x/development/tools/omv_rpc.html
Real docs: [Source Code on GH](https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault/usr/share/openmediavault/engined/rpc)

## Type of change

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [X] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs/pull/140) here: 
- [X] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/en/more/development/#service-widget-guidelines).
- [X] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2023-08-12 09:24 UTC, userXinos commented
I would like to discuss which widget methods should be implemented next. I don’t see any reason to implement CPU Utilization, Memory from the dashboard, since the glances widget provides more functions and an excellent implementation, plus both widgets return one method from the back end, i.e. if you could dine them into a group so as not to spam with a FULL_SYS_INFO request ...

2023-08-12 09:28 UTC, userXinos commented
When Homepage TypeScript

2023-08-12 11:40 UTC, benphelps commented
> When Homepage TypeScript

When someone does all the work and makes a PR for it, and has enough interest. We'd have to come to some agreement on what required engagement from the community to constitute a "majority" looks like.


Then given a "majority" of the community is interested in converting to TS; give the members a few weeks to review it, test it, etc., which would require a notice to freeze development until the review is complete and merged or otherwise.

It would be a tremendous amount of effort, esp. given the number of widgets currently under maintenance.

2023-08-12 12:00 UTC, userXinos commented
I just asked in the plan if there were any plans for this or something like that without pretensions.

2023-08-12 13:58 UTC, shamoon requested changes
Thanks for the PR. A couple things:

- The widget should use normal "blocks", not implement its own style. We've come upon this issue before, but we prioritize consistency.
- Please revert the linting changes, it sorta muddies this PR

Also, since OMV setup isn't so trivial, if you could please provide some samples of API endpoints for testing, thanks.

2023-08-12 14:28 UTC, userXinos commented
![изображение](https://github.com/benphelps/homepage/assets/40886699/fe72256a-546d-495d-999a-d03f4777dead)

1) I just copied the style from the OMV dashboard, which widget should I pay attention to to implement this functionality? Or to do the normal text list ?

2023-08-12 14:53 UTC, userXinos commented
[http.zip](https://github.com/benphelps/homepage/files/12327586/http.zip)

2023-08-12 14:56 UTC, shamoon commented
Thanks. Yea the text "block" widgets.

2023-08-12 15:33 UTC, userXinos commented
![изображение](https://github.com/benphelps/homepage/assets/40886699/5dce15c6-ee54-43d1-88c0-82ef746a7596)

Current state. ~~Not so much fun~~

2023-08-12 15:39 UTC, shamoon commented
Sorry, to clarify, they should be some version of e.g:, just like the downloader one
```
    <Container service={service}>
       <Block label=..." value={...} />
       <Block label="..." value={...} />
     </Container>
```

This is how fields filtering works and its the standard for all service widgets.

I'll leave it up to you how to handle that, if you list the number of drives with SMART OK, services up / total, or whatever. Personally I would merge the widgets into one and support different fields (with a default limited to max 4 as in the guidelines). An example like this is the gamedig widget: https://github.com/benphelps/homepage/pull/1717/files

2023-08-12 15:48 UTC, userXinos commented
alright

2023-08-12 16:03 UTC, userXinos commented
![изображение](https://github.com/benphelps/homepage/assets/40886699/8c06dcd2-8b20-4a1d-87e1-74e274cb81b6)

2023-08-13 15:26 UTC, shamoon approved these changes
Thanks for your flexibility, this is great overall. I made some relatively minor changes (some needed, like placing error handling before the items manipulation, unique translation strings, etc). Please let me know if you have any concerns

<img width="591" alt="Screenshot 2023-08-13 at 8 19 22 AM" src="https://github.com/benphelps/homepage/assets/4887959/1711a351-b764-4c91-87e8-35a9b32fb99c">
<img width="602" alt="Screenshot 2023-08-13 at 8 18 46 AM" src="https://github.com/benphelps/homepage/assets/4887959/bc1a2101-981c-43a8-9121-8bf7b55ab50d">
<img width="591" alt="Screenshot 2023-08-13 at 8 09 47 AM" src="https://github.com/benphelps/homepage/assets/4887959/c16207b7-561c-4443-959a-b7bd68bc94b3">

2023-08-13 15:35 UTC, userXinos commented on src/widgets/openmediavault/components/total_numbers.jsx
why not

2023-08-13 15:41 UTC, shamoon commented on src/widgets/openmediavault/components/total_numbers.jsx
To put the error output above the items.reduce calls. I also just find it a bit less convoluted. I realize of course there is some code repetition but minimal.

2023-08-13 15:46 UTC, userXinos commented
I was hoping that the members of the discussion would like to see some of the methods released. I will implement a few later. Can I use the graphics widget style from Glances Widget for this ?
![изображение](https://github.com/benphelps/homepage/assets/40886699/27ab73a7-4605-4d5e-a6c3-536e8a59afaf)

2023-08-13 15:58 UTC, shamoon commented
Yes you can use the charts or the standard ones. Im happy to merge this in the meantime if you’re good with it

2023-08-14 00:33 UTC, merged

2023-09-20 21:44 UTC, Mbarmem commented
> getInformation

Hi, would you mind sharing the code for pulling CPU & Memory usage.

I am using OMV on a different system and would love to implement it.

2023-09-20 21:45 UTC, Mbarmem commented
> I would like to discuss which widget methods should be implemented next. I don’t see any reason to implement CPU Utilization, Memory from the dashboard, since the glances widget provides more functions and an excellent implementation, plus both widgets return one method from the backend, i.e. if you could dine them into a group so as not to spam with a FULL_SYS_INFO request ... .
> 
> Network Developer Tools: `[POST] {"service":"System","method":"getInformation"...}` ![изображение](https://user-images.githubusercontent.com/40886699/260219110-c6687d90-0f4a-47d6-a9b9-978487b7883f.png)

Hi, would you mind sharing the code for pulling CPU & Memory usage.

I am using OMV on a different system and would love to implement it.

2023-09-21 01:35 UTC, userXinos commented
@Mbarmem 

I don't have such code, can you see something similar in the glances widget?