OpenMediaVault widget: Part 2
benphelps/homepage pull request #1817
Opened 2023-08-16 11:03 UTC by userXinos

## Proposed change

Sequel #1807 

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [ ] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: 
- [ ] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/en/more/development/#service-widget-guidelines).
- [X] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2023-08-16 11:10 UTC, userXinos commented
[http.zip](https://github.com/benphelps/homepage/files/12358605/http.zip)

2023-08-16 23:04 UTC, shamoon commented
Since there havent been requests specifically for either of these:

Feels like updates in an info widget is weird, I think of those for persistently-relevant data. I wonder if would be better as another service widget option.

ZFS charts one is cool because charts are cool but I wonder how meaningful it is, again there was no discussion on these.

Overall Im a little concerned because it feels like we already do / would have even more of a large amount of OMV-related code to maintain, imbalanced with most other services we support, for something that I suspect is not used by the vast majority of [our] users based off votes etc

Welcome your thoughts

2023-08-17 07:03 UTC, userXinos commented
The update widget will then look like this, is it really necessary in this form?  As an info widget, I thought it would be more accurate.
![Screenshot_20230817_133105](https://github.com/benphelps/homepage/assets/40886699/89c7372a-ea61-4504-a997-b203e501d21b)

ZFS, these charts are also in TrueNas, it seems there is some demand, why not port them

I'm not sure that the implementation of endpoints will be expensive, because so far this is a copy-paste to a large extent. 

If there is some kind of off-limit on the number of endpoints, then ok, I just implemented what I'm interested in and in this part, what's interesting is secondary.  I thought to keep the first (then this) PR open, so as not to be accepted and used as a draft.

2023-08-17 07:21 UTC, shamoon commented
There may be demand for ZFS data on a truenas dashboard which is a dedicated space for that but not necessarily the same in homepage... Homepage does not aim to be an "everything" command center, more a very nice dashboard with some useful info.

My biggest concern is code maintenance, etc. This is a lot of code for just one ecosystem used by a minority of users (I think).

My suggestion would be to move the updates info into an (option) of the service widget and drop the graph widget.

2023-08-17 08:27 UTC, userXinos commented
Oh, this ?
![изображение](https://github.com/benphelps/homepage/assets/40886699/832d855f-4612-47a8-9102-40335d5a2d83)

2023-08-17 13:59 UTC, shamoon requested changes
Yea thats great, thanks.

Small thing is to remove these IDE comments. 

If youre ready you can mark this as such and Im happy to test it out / merge

2023-08-17 13:59 UTC, shamoon commented on src/widgets/openmediavault/proxy.js
> +// noinspection DuplicatedCode
```suggestion
```

2023-08-17 13:59 UTC, shamoon commented on src/widgets/openmediavault/methods/smart_get_list.jsx
> +
```suggestion
```

2023-08-17 13:59 UTC, shamoon commented on src/widgets/openmediavault/methods/downloader_get_downloadlist.jsx
> +
```suggestion
```

2023-08-17 13:59 UTC, shamoon commented on src/widgets/openmediavault/methods/apt_enumerateUpgraded.jsx
> +
```suggestion
```

2023-08-17 13:59 UTC, shamoon commented on src/widgets/openmediavault/methods/downloader_get_downloadlist.jsx
> +// noinspection DuplicatedCode
```suggestion
```

2023-08-17 13:59 UTC, shamoon commented on src/widgets/openmediavault/methods/services_get_status.jsx
> +// noinspection DuplicatedCode
```suggestion
```

2023-08-17 13:59 UTC, shamoon commented on src/widgets/openmediavault/methods/apt_enumerateUpgraded.jsx
> +// noinspection DuplicatedCode
```suggestion
```

2023-08-26 06:25 UTC, shamoon commented
@userXinos Im not clear how much demand there is for these options, of course lets please re-address if there is more interest from the discussion(s).

Thanks again

2023-08-26 06:25 UTC, closed without merging

2023-08-26 06:28 UTC, userXinos commented
oh, alright