Feature: Added support to watchtower statistics
benphelps/homepage pull request #455
Opened 2022-10-26 20:27 UTC by FauFra

Added widget support for watchtower statistics.

How to use:
- Launch watchtower with the two commands `--http-api-metrics`  `--http-api-token` and bind port `8080` as described [here](https://containrrr.dev/watchtower/metrics/). 
```
 run -d \                                                            
  -v /var/run/docker.sock:/var/run/docker.sock \
 -p 8080:8080 containrrr/watchtower --http-api-metrics --http-api-token demotoken
```
- Then add the widget in the `services.yml` file, as shown below:
```
 - WatchTower:
        icon: watchtower.png
        server: my-docker
        container: watchtower
        widget:
            type: watchtower
            url: http://your-ip-address:8080
            key: demotoken
```

Preview:
![image](https://user-images.githubusercontent.com/33847731/198130189-54316c46-3cec-40be-8285-86ceae0c9298.png)

2022-10-26 20:35 UTC, shamoon commented
Thanks for the PR, please revert changes to the language files other then en, the others are updated through the weblate platform.

Myself (or someone else) will review this asap

2022-10-26 20:39 UTC, FauFra commented
Oh, I didn't know it, thanks.

2022-10-26 20:39 UTC, JazzFisch commented
Is there a way to make the labels clearer?  I recognize that naming things is hard, and it might not be possible to make clearer, however without clearer labels, translators will have a harder time coming up with good translations.

2022-10-26 20:50 UTC, FauFra commented
The first statistic indicates the number of times a scan is performed by the service, while the other ones refer to the number of containers scanned, updated and failed in the last scan. 

I wanted to add both types of statistics, but I recognize that this can create confusion and not clear labels.

Removing the first statistic and using `scanned` `updated` and `failed` as labels for the rest of the statistics should be more clear. What do you think?

2022-10-26 20:51 UTC, shamoon commented
Yea that makes sense to me. Curious, what do you link to with a watchtower widget, anything?

2022-10-26 21:00 UTC, FauFra commented
Sorry, English is not my primary language. What do you mean by your question? Which watchtower's API do I use to get the values?

2022-10-26 21:46 UTC, shamoon commented
It’s not so important, just curious whether you would use this without an `href`, as in just to see the widget stats but no link (like in your example config above)

2022-10-27 19:47 UTC, shamoon requested changes
When you have a chance, please address the comments above, removing all common.json changes except for en and reworking the field names, etc. Thanks!

2022-10-27 20:25 UTC, FauFra commented
I did the changes, but before to commit I wanted to test everything inside a container. Unfortunately, I have some troubles with docker buildx build. 

```
=> ERROR [builder 5/5] RUN <<EOF (set -xe...)                                                                                                                                                                                                                                                                                                                   38.9s
------                                                                                                                                                                                                                                                                                                                                                                 
 > [builder 5/5] RUN <<EOF (set -xe...):                                                                                                                                                                                                                                                                                                                               
#0 0.506 + npm run telemetry                                                                                                                                                                                                                                                                                                                                           
#0 0.988                                                                                                                                                                                                                                                                                                                                                               
#0 0.988 > startpage@0.1.0 telemetry
#0 0.988 > next telemetry disable
#0 0.988 
#0 1.151 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#0 1.155 This information is used to shape Next.js' roadmap and prioritize features.
#0 1.155 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#0 1.156 https://nextjs.org/telemetry
#0 1.156 
#0 1.164 Your preference has been saved to /app/cache/config.json.
#0 1.164 
#0 1.164 Status: Disabled
#0 1.164 
#0 1.164 You have opted-out of Next.js' anonymous telemetry program.
#0 1.164 No data will be collected from your machine.
#0 1.165 Learn more: https://nextjs.org/telemetry
#0 1.165 
#0 1.202 + mkdir config
#0 1.205 + echo -
#0 1.205 + NEXT_PUBLIC_BUILDTIME= NEXT_PUBLIC_VERSION= NEXT_PUBLIC_REVISION= npm run build
#0 1.677 
#0 1.677 > startpage@0.1.0 build
#0 1.677 > next build
#0 1.677 
#0 2.172 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#0 2.173 This information is used to shape Next.js' roadmap and prioritize features.
#0 2.173 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#0 2.173 https://nextjs.org/telemetry
#0 2.173 
#0 2.343 info  - Linting and checking validity of types...
#0 10.43 info  - Creating an optimized production build...
#0 10.56 info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
#0 11.30 info  - Using external babel configuration from /app/.babelrc
#0 37.36 info  - Compiled successfully
#0 37.37 info  - Collecting page data...
#0 38.64 
#0 38.64 > Build error occurred
#0 38.64 [Error: ENOENT: no such file or directory, copyfile '/app/node_modules/styled-jsx/style.js' -> '/app/.next/standalone/node_modules/styled-jsx/style.js'] {
#0 38.64   errno: -2,
#0 38.64   code: 'ENOENT',
#0 38.64   syscall: 'copyfile',
#0 38.64   path: '/app/node_modules/styled-jsx/style.js',
#0 38.64   dest: '/app/.next/standalone/node_modules/styled-jsx/style.js'
#0 38.64 }
------
ERROR: failed to solve: executor failed running [/bin/sh -c     set -xe
    npm run telemetry
    mkdir config && echo '-' > config/settings.yaml
    NEXT_PUBLIC_BUILDTIME=$BUILDTIME NEXT_PUBLIC_VERSION=$VERSION NEXT_PUBLIC_REVISION=$REVISION npm run build
]: exit code: 1
```

Docker version: 20.10.18
Docker buildx version: 0.9.1

2022-10-27 20:28 UTC, shamoon commented
Yes, the build isnt working right now unfortunately, unclear issues with the arm builds. No ETA yet, but thanks for your patience. Its still easy enough to test locally but up to you

2022-10-27 20:48 UTC, shamoon commented on public/locales/bg/common.json
> -        "approvedPushes": "Approved"
You need to revert the changes you made to the language files (except en), squash and force-push. If that doesnt work perhaps just open a new PR, at the moment this PR is changing files you dont intend

2022-10-27 20:51 UTC, FauFra commented on public/locales/bg/common.json
> -        "approvedPushes": "Approved"
Yeah, I messed up with the merging phase, sorry. I try to fix it, otherwise, I will publish a new PR, as you suggested.

2022-10-27 21:55 UTC, FauFra commented on public/locales/bg/common.json
> -        "approvedPushes": "Approved"
Ok, now it should be okay. Let me know.

2022-10-28 08:00 UTC, merged

2022-10-28 08:00 UTC, shamoon commented
Great, thanks for the PR