OPNSense widget
benphelps/homepage pull request #730
Opened 2022-12-25 19:16 UTC by Oupsman

First working version of OPNsense widget. CPU and memory usage are not quite reliable yet.

2022-12-25 19:21 UTC, shamoon commented
Cool. Why are cpu and memory unreliable? Regex matching in general isn’t the most reliable thing but sometimes unavoidable

2022-12-25 19:24 UTC, Oupsman commented
> Cool. Why are cpu and memory unreliable? Regex matching in general isn’t the most reliable thing but sometimes unavoidable

Well, CPU usage sometime displays "NaN" and I can't understand why. The memory usage displayed by the widget is not the same as in the dashboard. Values returned by the API call are not the same. I've asked why on the OPNsense forum. If I don't get any answer, I think I'll have to write a special proxy for OPNsense and call the widget API, which is not callable in API mode (you have to be logged on the firewall interface to call it).

2022-12-25 19:44 UTC, shamoon commented
Gotcha. In general we prefer widgets to not use their own proxy if possible, hugely reduces code maintenance, errors, etc

Once I figure out how to get one of these setup I can test and review

2022-12-25 19:48 UTC, Oupsman commented
> Gotcha. In general we prefer widgets to not use their own proxy if possible, hugely reduces code maintenance, errors, etc
> 

That's what I thought and honestly, I would really prefer it without a proxy.js file. I've found the reason why the CPU value is unreliable, my split code is wrong : sometime, values are separated by two spaces, and sometime, not. So I think I'll use substr instead.

2022-12-25 23:00 UTC, shamoon requested changes
Overall nice, works great.

I think the calculations are overkill, I would just change to using the statistics reported from the api.

I also think that 5 blocks gets pretty cramped (see below) so I would advocate for reducing this by at least 1. In fact I would say to remove the WAN data and then you can remove the second API call to keep things speedier. But up to you on that last point, I didnt include it in the suggestions.

<img width="433" alt="Screen Shot 2022-12-25 at 2 58 15 PM" src="https://user-images.githubusercontent.com/4887959/209483959-eb16c99e-39c6-49db-8570-e70e0afb7c89.png">

2022-12-25 23:12 UTC, shamoon requested changes
couple other random things

2022-12-25 23:12 UTC, shamoon commented on src/widgets/opnsense/component.jsx
> +  const uptime = uptimeInfos[1];
```suggestion
  const uptime = activityData.headers[0].match(/.* up ([0-9+:]*) .*/)[1];
```

Oh, and since youre not checking to make sure these values return, you might as well just collapse the code

2022-12-25 23:12 UTC, shamoon commented on src/widgets/opnsense/widget.js
> +      endpoint: "diagnostics/activity/getActivity",
```suggestion
      endpoint: "diagnostics/activity/getActivity",
      validate: [
        "headers"
      ]
```

As with others, can probably add a validate param

2022-12-26 06:04 UTC, Oupsman commented on src/widgets/opnsense/component.jsx
> +  const memory = ( 1 - parseFloat(memoryInfos[11]) / totalMemory) * 100;
Here is the header coming from my firewall : 
Mem: 228M Active, 257M Inact, 3850M Laundry, 2539M Wired, 1832K Buf, 961M Free

I want to report the used memory in percent because it's more meaningful to have this value. 

The api call from the widget API just gives two values : 

{
	"memory": {
		"total": "8461099008",
		"used": "7799020107"
	}
}

and the widget reports a memory usage of 91% 

at the same time, my code reports a memory usage of 97%, that's why I say that this is inaccurate.

2022-12-26 06:04 UTC, Oupsman commented on src/widgets/opnsense/component.jsx
> +  const cpu = parseFloat(cpuInfos[2]) + parseFloat(cpuInfos[5]) + parseFloat(cpuInfos[8]) + parseFloat(cpuInfos[11]);
I tried that but it wasn't reliable, it gived me 'Nan' from time to time and I changed it to the sum of the other values  (can't figured out why). As the string is fixed width, I'm using substring(60, 64) and I let it run for hours without getting a Nan value once.

2022-12-26 06:11 UTC, shamoon commented on src/widgets/opnsense/component.jsx
> +  const cpu = parseFloat(cpuInfos[2]) + parseFloat(cpuInfos[5]) + parseFloat(cpuInfos[8]) + parseFloat(cpuInfos[11]);
it’s too fragile to use an indexed substring. I find it hard to imagine why this regex would fail

2022-12-26 06:12 UTC, shamoon commented on src/widgets/opnsense/component.jsx
> +  const memory = ( 1 - parseFloat(memoryInfos[11]) / totalMemory) * 100;
Again, keep it simple I think

2022-12-26 06:22 UTC, Oupsman commented
> I also think that 5 blocks gets pretty cramped (see below) so I would advocate for reducing this by at least 1. In fact I would say to remove the WAN data and then you can remove the second API call to keep things speedier. But up to you on that last point, I didnt include it in the suggestions.

That is the data requested in the enhancement request. 

But I'm wondering if the uptime is really that important a data to see : if the firewall were to reboot, the WAN datas will be reset to zero at the reboot moment so you'll see a huge decrease on the widget.

2022-12-26 06:25 UTC, shamoon commented
> But I'm wondering if the uptime is really that important a data to see : if the firewall were to reboot, the WAN datas will be reset to zero at the reboot moment so you'll see a huge decrease on the widget.

Yea but as the widget author it’s really up to you :)

2022-12-26 07:05 UTC, shamoon commented
Mate, you asked for feedback and are ignoring it even though you mentioned not being very comfortable with JS. We appreciate your contribution but please understand that part of the job here is to try and maintain consistent code quality.

The memory calc isnt working in my testing.

<img width="546" alt="Screen Shot 2022-12-25 at 10 45 01 PM" src="https://user-images.githubusercontent.com/4887959/209515359-a3ace79e-9f87-4d3d-b8cc-32d0a214df63.png">

Again, my suggestions are meant to simplify your code and make it less error-prone. Please adjust.

2022-12-26 07:15 UTC, Oupsman commented on src/widgets/opnsense/component.jsx
> +  const cpu = parseFloat(cpuInfos[2]) + parseFloat(cpuInfos[5]) + parseFloat(cpuInfos[8]) + parseFloat(cpuInfos[11]);
> Mate, you asked for feedback and are ignoring it even though you mentioned not being very comfortable with JS. We appreciate your contribution but please understand that part of the job here is to try and maintain consistent code quality.
> 
> The memory calc isnt working in my testing.
> 
> <img alt="Screen Shot 2022-12-25 at 10 45 01 PM" width="546" src="https://user-images.githubusercontent.com/4887959/209515359-a3ace79e-9f87-4d3d-b8cc-32d0a214df63.png">
> 
> Again, my suggestions are meant to simplify your code and make it less error-prone. Please adjust.

I agree, that's why I needed testing : it works on both of my opnsense firewalls, but if it doesn't work on yours, it's not reliable so I think I'll just drop the memory code for now.

2022-12-26 07:30 UTC, Oupsman commented
> Mate, you asked for feedback and are ignoring it even though you mentioned not being very comfortable with JS. We appreciate your contribution but please understand that part of the job here is to try and maintain consistent code quality.
> 
> The memory calc isnt working in my testing.
> 
> <img alt="Screen Shot 2022-12-25 at 10 45 01 PM" width="546" src="https://user-images.githubusercontent.com/4887959/209515359-a3ace79e-9f87-4d3d-b8cc-32d0a214df63.png">
> 
> Again, my suggestions are meant to simplify your code and make it less error-prone. Please adjust.

I am trying the regex to get the idle value right now. Sorry if you thought I'm not taking your advice into account, I'm trying to keep up with you, on the contrary.

2022-12-26 07:30 UTC, shamoon commented
It was a code suggestion above, you can just apply suggestions using the GH site

2022-12-26 07:31 UTC, shamoon commented on src/widgets/opnsense/component.jsx
> +  const cpu = 100 - parseFloat(cpuidle);
```suggestion
  const cpuIdle = activityData.headers[2].match(/ ([0-9.]+)% idle/)[1];
  const cpu = 100 - parseFloat(cpuIdle);
```

2022-12-26 08:02 UTC, shamoon commented
Let me know if youre still working on this (obviously if youre offline no worries)

2022-12-26 08:04 UTC, Oupsman commented
> Let me know if youre still working on this (obviously if youre offline no worries)

I have to work (holidays are over) but I think I'll work on it in the evening. As the memory code is really unreliable (as per your testings, I'm not the only one in this case) I think I'm going to drop it, because I think it's better to report no value than a unreliable value.

2022-12-26 08:13 UTC, shamoon commented
> > Let me know if youre still working on this (obviously if youre offline no worries)
> 
> I have to work (holidays are over) but I think I'll work on it in the evening. As the memory code is really unreliable (as per your testings, I'm not the only one in this case) I think I'm going to drop it, because I think it's better to report no value than a unreliable value.

I agree. That change is also a suggestion here, if you dont mind we can apply and get this merged and done.

2022-12-26 08:16 UTC, Oupsman commented
> > > Let me know if youre still working on this (obviously if youre offline no worries)
> > 
> > 
> > I have to work (holidays are over) but I think I'll work on it in the evening. As the memory code is really unreliable (as per your testings, I'm not the only one in this case) I think I'm going to drop it, because I think it's better to report no value than a unreliable value.
> 
> I agree. That change is also a suggestion here, if you dont mind we can apply and get this merged and done.

If I understand correctly, your proposition is to report the active memory, and I don't think that's a meaningful value. I'm more into purely stopping to report memory usage until I have a reliable way to retrieve it.

2022-12-26 08:22 UTC, shamoon commented
> If I understand correctly, your proposition is to report the active memory, and I don't think that's a meaningful value. I'm more into purely stopping to report memory usage until I have a reliable way to retrieve it.

I mean, if you feel strongly OK, but I would think most people would find the active memory value more useful than nothing, no?

2022-12-26 08:28 UTC, Oupsman commented
> > If I understand correctly, your proposition is to report the active memory, and I don't think that's a meaningful value. I'm more into purely stopping to report memory usage until I have a reliable way to retrieve it.
> 
> I mean, if you feel strongly OK, but I would think most people would find the active memory value more useful than nothing, no?

That's a valid point, I've validated your commits.

2022-12-26 08:32 UTC, shamoon commented
Cheers, thanks for all the effort

2022-12-26 08:32 UTC, merged