Add Moonraker (Klipper) widget
benphelps/homepage pull request #798
Opened 2023-01-10 14:09 UTC by Eizock

I've added support for displaying prinstatus from Klipper via Moonraker.
To use it:
`type: moonraker`
`url: http://ip.to.your.moonraker:port`

2023-01-10 16:34 UTC, shamoon requested changes
There are some linting things to fix but also this is another one it looks like we wont be able to test easily. Would you mind posting some sample output from the API at least?

2023-01-10 19:40 UTC, Eizock commented
Apologies, for the avoidable linting errors. I'm quite new to linting in general.
The linting errors should now be fixed.

Here are sample outputs of the API endpoints.
<details>
  <summary>print_stats</summary>

  ```json
  {
    "result": {
      "status": {
        "print_stats": {
          "info": {
            "total_layer": null,
            "current_layer": null
          },
          "print_duration": 4885.865378969,
          "total_duration": 5133.010960750005,
          "filament_used": 9796.927220000001,
          "filename": "SC846_SSD_HDD_Holder.gcode",
          "state": "complete",
          "message": ""
        }
      },
      "eventtime": 248270.603765604
    }
  }
  ```
</details>

<details>
  <summary>display_status</summary>

  ```json
  {
    "result": {
      "status": {
        "display_status": {
          "progress": 1,
          "message": null
        }
      },
      "eventtime": 248284.897741016
    }
  }
  ```
</details>

<details>
  <summary>webhooks</summary>

  ```json
  {
    "result": {
      "status": {
        "webhooks": {
          "state": "shutdown",
          "state_message": "Lost communication with MCU 'mcu'\nOnce the underlying issue is corrected, use the\n\"FIRMWARE_RESTART\" command to reset the firmware, reload the\nconfig, and restart the host software.\nPrinter is shutdown\n"
        }
      },
      "eventtime": 253881.55679112
    }
  }
  ```
</details>

2023-01-10 19:45 UTC, JazzFisch commented
@Eizock 5 fields can be pretty busy on a widget.  Can you also provide some images of it running?

2023-01-10 19:51 UTC, Eizock commented
![image](https://user-images.githubusercontent.com/8332480/211648333-7c1480a7-d668-422c-a5a1-9587fba9ddff.png)

I tried styling it so it doesn't look too busy.
Alternatively i could only display Printer Status if it's offline and display the rest instead if it's online.

2023-01-10 19:54 UTC, shamoon commented
Ah yea we shoot for 4 max as horizontal blocks, perhaps drop one

2023-01-10 20:35 UTC, Eizock commented
![image](https://user-images.githubusercontent.com/8332480/211655039-de9e877b-25e0-418e-b42f-4ded37ac4d08.png)
![image](https://user-images.githubusercontent.com/8332480/211655142-598c62d0-238e-4f64-910b-9a76119b54c5.png)

I ditched the filename entirely and made it, that if the printer is offline it only shows status (upper image).
And if it is online, it shows layers, progress and the status of the print (lower image).

2023-01-10 21:01 UTC, JazzFisch commented
As you are no longer using the filename field, can you please remove the entry from common.json?

2023-01-10 21:05 UTC, Eizock commented
Yeah, i noticed aswell. Sorry for that.

2023-01-10 21:36 UTC, shamoon commented
My only other question is how much interest there is for this (besides you =), I honestly dont know. Theres only one discussion about 3d print monitoring and sounds like they weren't using this tool. #250

2023-01-11 08:42 UTC, Eizock commented
The mentioned Mainsail and/or Fluidd is the UI, Moonraker provides the actual API to connect to Klipper and Klipper is the firmware. :D 
See [Mainsail-Docs](https://docs.mainsail.xyz/setup/manual-setup/moonraker) and [Fluidd-Docs](https://docs.fluidd.xyz/configuration/moonraker) and [Moonraker](https://github.com/Arksine/moonraker).

2023-01-11 21:57 UTC, shamoon commented
Thanks for clarifying that, you 3d printers weave a tangled web (pun?)

One thing in testing, can you send an example API output for printStats when things are going? are the `total_layer` and `current_layer` properties passed as strings or numbers? there may be an issue there

2023-01-11 22:01 UTC, shamoon requested changes

2023-01-11 22:01 UTC, shamoon commented on src/widgets/moonraker/component.jsx
> +  if(!printStats.result.status.print_stats.info.total_layer === "") {
```suggestion
  if (printStats.result.status.print_stats.info.total_layer !== "") {
```

I think should be this, at the moment youre (unintentionally) coercing the value to a boolean which doesnt really work. Depending on the type of the API output though there could be another way

2023-01-12 09:47 UTC, Eizock commented
We don't weave it, we print it. :P

Here is the requested sample output.
<details>
  <summary>print_stats</summary>

  ```json
  {
    "result": {
      "status": {
        "print_stats": {
        "info": {
            "total_layer": 361,
            "current_layer": 7
          },
          "print_duration": 0,
          "total_duration": 0,
          "filament_used": 0,
          "filename": "",
          "state": "standby",
          "message": ""
        }
      },
      "eventtime": 410808.673944955
    }
  }
  ```
</details>

2023-01-12 09:56 UTC, Eizock commented on src/widgets/moonraker/component.jsx
> +  if(!printStats.result.status.print_stats.info.total_layer === "") {
Yeah, i think you are right. TBH i don't know what my brain was thinking while i wrote that.
```suggestion
  if(printStats.result.status.print_stats.info.total_layer !== null) {
```
This should be even better since I am using strict equality and the API returns null instead of 0 if it has no layer information.

2023-01-12 21:51 UTC, shamoon commented
Sweet thanks!

2023-01-12 21:55 UTC, merged